[MeasureC1]
Measure=Plugin
Plugin=MSIAfterburner
DataSource=CPU1 usage
MinValue=0
MaxValue=100

[MeasureC2]
Measure=Plugin
Plugin=MSIAfterburner
DataSource=CPU2 usage
MinValue=0
MaxValue=100

[MeasureC3]
Measure=Plugin
Plugin=MSIAfterburner
DataSource=CPU3 usage
MinValue=0
MaxValue=100

[MeasureC4]
Measure=Plugin
Plugin=MSIAfterburner
DataSource=CPU4 usage
MinValue=0
MaxValue=100

[MeasureC5]
Measure=Plugin
Plugin=MSIAfterburner
DataSource=CPU5 usage
MinValue=0
MaxValue=100

[MeasureC6]
Measure=Plugin
Plugin=MSIAfterburner
DataSource=CPU6 usage
MinValue=0
MaxValue=100

[MeasureC7]
Measure=Plugin
Plugin=MSIAfterburner
DataSource=CPU7 usage
MinValue=0
MaxValue=100

[MeasureC8]
Measure=Plugin
Plugin=MSIAfterburner
DataSource=CPU8 usage
MinValue=0
MaxValue=100

[MeasureC9]
Measure=Plugin
Plugin=MSIAfterburner
DataSource=CPU9 usage
MinValue=0
MaxValue=100

[MeasureC10]
Measure=Plugin
Plugin=MSIAfterburner
DataSource=CPU10 usage
MinValue=0
MaxValue=100

[MeasureC11]
Measure=Plugin
Plugin=MSIAfterburner
DataSource=CPU11 usage
MinValue=0
MaxValue=100

[MeasureC12]
Measure=Plugin
Plugin=MSIAfterburner
DataSource=CPU12 usage
MinValue=0
MaxValue=100

[MeasureC13]
Measure=Plugin
Plugin=MSIAfterburner
DataSource=CPU13 usage
MinValue=0
MaxValue=100

[MeasureC14]
Measure=Plugin
Plugin=MSIAfterburner
DataSource=CPU14 usage
MinValue=0
MaxValue=100

[MeasureC15]
Measure=Plugin
Plugin=MSIAfterburner
DataSource=CPU15 usage
MinValue=0
MaxValue=100

[MeasureC16]
Measure=Plugin
Plugin=MSIAfterburner
DataSource=CPU16 usage
MinValue=0
MaxValue=100

[MeterCoresL]
Meter=String
X=16
Y=548
FontFace=Segoe UI
FontSize=8
FontColor=139,144,154
FontWeight=600
AntiAlias=1
Text=THREADS
Group=Cores
Hidden=1

[MeterC1]
Meter=Bar
MeasureName=MeasureC1
X=16
Y=564
W=40
H=10
BarColor=243,244,246
SolidColor=25,28,35
BarOrientation=Horizontal
Group=Cores
Hidden=1

[MeterC1N]
Meter=String
X=16
Y=576
FontFace=Consolas
FontSize=6
FontColor=92,97,107
AntiAlias=1
Text=1
Group=Cores
Hidden=1

[MeterC2]
Meter=Bar
MeasureName=MeasureC2
X=60
Y=564
W=40
H=10
BarColor=243,244,246
SolidColor=25,28,35
BarOrientation=Horizontal
Group=Cores
Hidden=1

[MeterC2N]
Meter=String
X=60
Y=576
FontFace=Consolas
FontSize=6
FontColor=92,97,107
AntiAlias=1
Text=2
Group=Cores
Hidden=1

[MeterC3]
Meter=Bar
MeasureName=MeasureC3
X=104
Y=564
W=40
H=10
BarColor=243,244,246
SolidColor=25,28,35
BarOrientation=Horizontal
Group=Cores
Hidden=1

[MeterC3N]
Meter=String
X=104
Y=576
FontFace=Consolas
FontSize=6
FontColor=92,97,107
AntiAlias=1
Text=3
Group=Cores
Hidden=1

[MeterC4]
Meter=Bar
MeasureName=MeasureC4
X=148
Y=564
W=40
H=10
BarColor=243,244,246
SolidColor=25,28,35
BarOrientation=Horizontal
Group=Cores
Hidden=1

[MeterC4N]
Meter=String
X=148
Y=576
FontFace=Consolas
FontSize=6
FontColor=92,97,107
AntiAlias=1
Text=4
Group=Cores
Hidden=1

[MeterC5]
Meter=Bar
MeasureName=MeasureC5
X=192
Y=564
W=40
H=10
BarColor=243,244,246
SolidColor=25,28,35
BarOrientation=Horizontal
Group=Cores
Hidden=1

[MeterC5N]
Meter=String
X=192
Y=576
FontFace=Consolas
FontSize=6
FontColor=92,97,107
AntiAlias=1
Text=5
Group=Cores
Hidden=1

[MeterC6]
Meter=Bar
MeasureName=MeasureC6
X=236
Y=564
W=40
H=10
BarColor=243,244,246
SolidColor=25,28,35
BarOrientation=Horizontal
Group=Cores
Hidden=1

[MeterC6N]
Meter=String
X=236
Y=576
FontFace=Consolas
FontSize=6
FontColor=92,97,107
AntiAlias=1
Text=6
Group=Cores
Hidden=1

[MeterC7]
Meter=Bar
MeasureName=MeasureC7
X=280
Y=564
W=40
H=10
BarColor=243,244,246
SolidColor=25,28,35
BarOrientation=Horizontal
Group=Cores
Hidden=1

[MeterC7N]
Meter=String
X=280
Y=576
FontFace=Consolas
FontSize=6
FontColor=92,97,107
AntiAlias=1
Text=7
Group=Cores
Hidden=1

[MeterC8]
Meter=Bar
MeasureName=MeasureC8
X=324
Y=564
W=40
H=10
BarColor=243,244,246
SolidColor=25,28,35
BarOrientation=Horizontal
Group=Cores
Hidden=1

[MeterC8N]
Meter=String
X=324
Y=576
FontFace=Consolas
FontSize=6
FontColor=92,97,107
AntiAlias=1
Text=8
Group=Cores
Hidden=1

[MeterC9]
Meter=Bar
MeasureName=MeasureC9
X=16
Y=592
W=40
H=10
BarColor=243,244,246
SolidColor=25,28,35
BarOrientation=Horizontal
Group=Cores
Hidden=1

[MeterC9N]
Meter=String
X=16
Y=604
FontFace=Consolas
FontSize=6
FontColor=92,97,107
AntiAlias=1
Text=9
Group=Cores
Hidden=1

[MeterC10]
Meter=Bar
MeasureName=MeasureC10
X=60
Y=592
W=40
H=10
BarColor=243,244,246
SolidColor=25,28,35
BarOrientation=Horizontal
Group=Cores
Hidden=1

[MeterC10N]
Meter=String
X=60
Y=604
FontFace=Consolas
FontSize=6
FontColor=92,97,107
AntiAlias=1
Text=10
Group=Cores
Hidden=1

[MeterC11]
Meter=Bar
MeasureName=MeasureC11
X=104
Y=592
W=40
H=10
BarColor=243,244,246
SolidColor=25,28,35
BarOrientation=Horizontal
Group=Cores
Hidden=1

[MeterC11N]
Meter=String
X=104
Y=604
FontFace=Consolas
FontSize=6
FontColor=92,97,107
AntiAlias=1
Text=11
Group=Cores
Hidden=1

[MeterC12]
Meter=Bar
MeasureName=MeasureC12
X=148
Y=592
W=40
H=10
BarColor=243,244,246
SolidColor=25,28,35
BarOrientation=Horizontal
Group=Cores
Hidden=1

[MeterC12N]
Meter=String
X=148
Y=604
FontFace=Consolas
FontSize=6
FontColor=92,97,107
AntiAlias=1
Text=12
Group=Cores
Hidden=1

[MeterC13]
Meter=Bar
MeasureName=MeasureC13
X=192
Y=592
W=40
H=10
BarColor=243,244,246
SolidColor=25,28,35
BarOrientation=Horizontal
Group=Cores
Hidden=1

[MeterC13N]
Meter=String
X=192
Y=604
FontFace=Consolas
FontSize=6
FontColor=92,97,107
AntiAlias=1
Text=13
Group=Cores
Hidden=1

[MeterC14]
Meter=Bar
MeasureName=MeasureC14
X=236
Y=592
W=40
H=10
BarColor=243,244,246
SolidColor=25,28,35
BarOrientation=Horizontal
Group=Cores
Hidden=1

[MeterC14N]
Meter=String
X=236
Y=604
FontFace=Consolas
FontSize=6
FontColor=92,97,107
AntiAlias=1
Text=14
Group=Cores
Hidden=1

[MeterC15]
Meter=Bar
MeasureName=MeasureC15
X=280
Y=592
W=40
H=10
BarColor=243,244,246
SolidColor=25,28,35
BarOrientation=Horizontal
Group=Cores
Hidden=1

[MeterC15N]
Meter=String
X=280
Y=604
FontFace=Consolas
FontSize=6
FontColor=92,97,107
AntiAlias=1
Text=15
Group=Cores
Hidden=1

[MeterC16]
Meter=Bar
MeasureName=MeasureC16
X=324
Y=592
W=40
H=10
BarColor=243,244,246
SolidColor=25,28,35
BarOrientation=Horizontal
Group=Cores
Hidden=1

[MeterC16N]
Meter=String
X=324
Y=604
FontFace=Consolas
FontSize=6
FontColor=92,97,107
AntiAlias=1
Text=16
Group=Cores
Hidden=1
